COMP: Disable ScanConvertPhasedArray3D image
To address: /usr/src/SlicerITKUltrasound/ScanConvertPhasedArray3D/ScanConvertPhasedArray3D.cxx:92:3:   required from ‘int {anonymous}::DoIt(int, char**) [with TPixel = unsigned char]’
/usr/src/SlicerITKUltrasound/ScanConvertPhasedArray3D/ScanConvertPhasedArray3D.cxx:120:50:   required from here
/usr/src/Slicer-build/ITKv4/Modules/Core/Common/include/itkImageBoundaryCondition.h:77:3: error: no type named ‘NeighborhoodAccessorFunctorType’ in ‘class itk::PhasedArray3DSpecialCoordinatesImage<unsigned char>’
   NeighborhoodAccessorFunctorType;
   ^

Slicer requires a version of ITK with this patch:

  http://review.source.kitware.com/#/c/21119/